/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AireAcondicionadoRouteImport } from './routes/aire-acondicionado'
import { Route as AvisoRouteImport } from './routes/aviso'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PanelMasAireRouteImport } from './routes/panel-mas-aire'
import { Route as PanelesSolaresRouteImport } from './routes/paneles-solares'
import { Route as PanelesSolaresAutonomosRouteImport } from './routes/paneles-solares-autonomos'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SolucionesEnElectricidadRouteImport } from './routes/soluciones-en-electricidad'
import { Route as SuccessRouteImport } from './routes/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AireAcondicionadoRoute = AireAcondicionadoRouteImport.update({
  id: '/aire-acondicionado',
  path: '/aire-acondicionado',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoRoute = AvisoRouteImport.update({
  id: '/aviso',
  path: '/aviso',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelMasAireRoute = PanelMasAireRouteImport.update({
  id: '/panel-mas-aire',
  path: '/panel-mas-aire',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelesSolaresRoute = PanelesSolaresRouteImport.update({
  id: '/paneles-solares',
  path: '/paneles-solares',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelesSolaresAutonomosRoute = PanelesSolaresAutonomosRouteImport.update({
  id: '/paneles-solares-autonomos',
  path: '/paneles-solares-autonomos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesEnElectricidadRoute =
  SolucionesEnElectricidadRouteImport.update({
    id: '/soluciones-en-electricidad',
    path: '/soluciones-en-electricidad',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aire-acondicionado': typeof AireAcondicionadoRoute
  '/aviso': typeof AvisoRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/nosotros': typeof NosotrosRoute
  '/panel-mas-aire': typeof PanelMasAireRoute
  '/paneles-solares': typeof PanelesSolaresRoute
  '/paneles-solares-autonomos': typeof PanelesSolaresAutonomosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/soluciones-en-electricidad': typeof SolucionesEnElectricidadRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aire-acondicionado': typeof AireAcondicionadoRoute
  '/aviso': typeof AvisoRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/nosotros': typeof NosotrosRoute
  '/panel-mas-aire': typeof PanelMasAireRoute
  '/paneles-solares': typeof PanelesSolaresRoute
  '/paneles-solares-autonomos': typeof PanelesSolaresAutonomosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/soluciones-en-electricidad': typeof SolucionesEnElectricidadRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aire-acondicionado': typeof AireAcondicionadoRoute
  '/aviso': typeof AvisoRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/nosotros': typeof NosotrosRoute
  '/panel-mas-aire': typeof PanelMasAireRoute
  '/paneles-solares': typeof PanelesSolaresRoute
  '/paneles-solares-autonomos': typeof PanelesSolaresAutonomosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/soluciones-en-electricidad': typeof SolucionesEnElectricidadRoute
  '/success': typeof SuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aire-acondicionado'
    | '/aviso'
    | '/contacto'
    | '/faq'
    | '/nosotros'
    | '/panel-mas-aire'
    | '/paneles-solares'
    | '/paneles-solares-autonomos'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/soluciones-en-electricidad'
    | '/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aire-acondicionado'
    | '/aviso'
    | '/contacto'
    | '/faq'
    | '/nosotros'
    | '/panel-mas-aire'
    | '/paneles-solares'
    | '/paneles-solares-autonomos'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/soluciones-en-electricidad'
    | '/success'
  id:
    | '__root__'
    | '/'
    | '/aire-acondicionado'
    | '/aviso'
    | '/contacto'
    | '/faq'
    | '/nosotros'
    | '/panel-mas-aire'
    | '/paneles-solares'
    | '/paneles-solares-autonomos'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/soluciones-en-electricidad'
    | '/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AireAcondicionadoRoute: typeof AireAcondicionadoRoute
  AvisoRoute: typeof AvisoRoute
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  NosotrosRoute: typeof NosotrosRoute
  PanelMasAireRoute: typeof PanelMasAireRoute
  PanelesSolaresRoute: typeof PanelesSolaresRoute
  PanelesSolaresAutonomosRoute: typeof PanelesSolaresAutonomosRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ServiciosRoute: typeof ServiciosRoute
  SolucionesEnElectricidadRoute: typeof SolucionesEnElectricidadRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aire-acondicionado': {
      id: '/aire-acondicionado'
      path: '/aire-acondicionado'
      fullPath: '/aire-acondicionado'
      preLoaderRoute: typeof AireAcondicionadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso': {
      id: '/aviso'
      path: '/aviso'
      fullPath: '/aviso'
      preLoaderRoute: typeof AvisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-mas-aire': {
      id: '/panel-mas-aire'
      path: '/panel-mas-aire'
      fullPath: '/panel-mas-aire'
      preLoaderRoute: typeof PanelMasAireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paneles-solares': {
      id: '/paneles-solares'
      path: '/paneles-solares'
      fullPath: '/paneles-solares'
      preLoaderRoute: typeof PanelesSolaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paneles-solares-autonomos': {
      id: '/paneles-solares-autonomos'
      path: '/paneles-solares-autonomos'
      fullPath: '/paneles-solares-autonomos'
      preLoaderRoute: typeof PanelesSolaresAutonomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones-en-electricidad': {
      id: '/soluciones-en-electricidad'
      path: '/soluciones-en-electricidad'
      fullPath: '/soluciones-en-electricidad'
      preLoaderRoute: typeof SolucionesEnElectricidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AireAcondicionadoRoute: AireAcondicionadoRoute,
  AvisoRoute: AvisoRoute,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  NosotrosRoute: NosotrosRoute,
  PanelMasAireRoute: PanelMasAireRoute,
  PanelesSolaresRoute: PanelesSolaresRoute,
  PanelesSolaresAutonomosRoute: PanelesSolaresAutonomosRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ServiciosRoute: ServiciosRoute,
  SolucionesEnElectricidadRoute: SolucionesEnElectricidadRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
